# Generated by Django 3.2.9 on 2021-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211121_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email #2'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон #2'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email #1'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон #1'),
        ),
    ]
