# Generated by Django 3.2.9 on 2021-11-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='news', verbose_name='Фото')),
                ('link', models.CharField(max_length=255, verbose_name='ссылка на проект')),
            ],
            options={
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
