# Generated by Django 3.2.9 on 2021-11-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(help_text='Загружайте только jpg и png формат изображении', upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, help_text='Например: https://www.youtube.com/', max_length=255, null=True, verbose_name='ссылка на проект'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(help_text='Например Заголовок: Сегодня все пришли на урок', max_length=255, verbose_name='Название'),
        ),
    ]
